FROM python:3.9-slim

WORKDIR /app

COPY gateway-requirements.txt .
RUN pip install --no-cache-dir -r gateway-requirements.txt

COPY calculator.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. calculator.proto

COPY gateway.py .

EXPOSE 8080

CMD ["python", "gateway.py"]