FROM python:3.9-slim

WORKDIR /app

COPY gateway-requirements.txt .
RUN pip install --no-cache-dir -r gateway-requirements.txt

COPY simple-counter.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. simple-counter.proto

COPY gateway.py .

EXPOSE 8090

CMD ["python", "gateway.py"]