FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY simple-counter.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. simple-counter.proto

COPY counter_server.py .

EXPOSE 50055

CMD ["python", "counter_server.py"]